# Generated by Django 3.2.20 on 2023-08-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230823_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingriedient',
            new_name='Ingredient',
        ),
    ]
